/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-sync-scripts */
import "./globals.css";
import type { Metadata } from "next";
import NextAuthProvider from "@/components/NextAuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { GeistSans } from "geist/font/sans";
import Script from "next/script";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  icons: {
    icon: [
      {
        url: "/static/images/favicon.png",
        href: "/static/images/favicon.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>
          Jerrydata | AI-Driven Story-Based Business Intelligence Platform
        </title>
        <meta
          content="Are you tired of drowning in data and struggling to find the insights that matter? Say goodbye to endless visualizations and hello to actionable stories that drive real results."
          name="description"
        />
        <meta
          content="Jerrydata | AI-Driven Story-Based Business Intelligence Platform"
          property="og:title"
        />
        <meta
          content="Are you tired of drowning in data and struggling to find the insights that matter? Say goodbye to endless visualizations and hello to actionable stories that drive real results."
          property="og:description"
        />
        <meta
          content="https://uploads-ssl.webflow.com/65cda09b8c28f4e0438a9447/65ce19db95a90ec89fe3bba1_open-graph.webp"
          property="og:image"
        />
        <meta
          content="Jerrydata | AI-Driven Story-Based Business Intelligence Platform"
          property="twitter:title"
        />
        <meta
          content="Are you tired of drowning in data and struggling to find the insights that matter? Say goodbye to endless visualizations and hello to actionable stories that drive real results."
          property="twitter:description"
        />
        <meta
          content="https://uploads-ssl.webflow.com/65cda09b8c28f4e0438a9447/65ce19db95a90ec89fe3bba1_open-graph.webp"
          property="twitter:image"
        />
        <meta property="og:type" content="website" />
        <meta content="summary_large_image" name="twitter:card" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link
          href="https://fonts.gstatic.com"
          rel="preconnect"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Text:ital@0;1&family=Protest+Revolution&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="/static/images/favicon.png"
          rel="shortcut icon"
          type="image/x-icon"
        />
        <link href="/static/images/webclip.png" rel="apple-touch-icon" />
        <Script
          id="google-tag-manager"
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `<!-- Google Tag Manager -->
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-MDSS9MK5');
            <!-- End Google Tag Manager -->`,
          }}
        ></Script>
      </head>
      <body className={`${GeistSans.className} -tracking-[1%]`}>
        {/* <!-- Google Tag Manager (noscript) --> */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-MDSS9MK5"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        {/* <!-- End Google Tag Manager (noscript) --> */}
        <NextAuthProvider>{children}</NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
