import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: any = await getServerSession(authOptions);
  const userId = session?.user?._id || session?.user?.id;
  const name = session?.user?.name;

  return (
    <section className={`bg-[#F6F8FA] min-h-screen`}>
      <Navbar name={name} />
      <main className="pt-14">{children}</main>
    </section>
  );
}
